-- MySQL Script generated by MySQL Workbench
-- ter 17 out 2017 15:45:44 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`itens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`itens` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`itens` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NULL,
  `type` ENUM('HIGIENE', 'VEG', 'OPC', 'SAL', 'SOB', 'ACO') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `name_UNIQUE` ON `mydb`.`itens` (`name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`meals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`meals` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`meals` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `type` ENUM('ALMOCO', 'JANTA') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`menus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`menus` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`menus` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `itens_id` INT(11) NOT NULL,
  `meals_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `meals_id`),
  CONSTRAINT `fk_menus_itens`
    FOREIGN KEY (`itens_id`)
    REFERENCES `mydb`.`itens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menus_meals1`
    FOREIGN KEY (`meals_id`)
    REFERENCES `mydb`.`meals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_menus_meals1_idx` ON `mydb`.`menus` (`meals_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `matr` VARCHAR(45) NOT NULL,
  `password` CHAR(128) NOT NULL,
  `role` ENUM('ADM', 'USER') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comments` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`comments` (
  `id` INT(11) NOT NULL,
  `comment` VARCHAR(280) NOT NULL,
  `users_id` INT(11) NOT NULL,
  `meals_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_meals1`
    FOREIGN KEY (`meals_id`)
    REFERENCES `mydb`.`meals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_comments_users1_idx` ON `mydb`.`comments` (`users_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_comments_meals1_idx` ON `mydb`.`comments` (`meals_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`grades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`grades` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`grades` (
  `menus_id` INT(11) NOT NULL,
  `users_id` INT(11) NOT NULL,
  `value` INT NOT NULL,
  PRIMARY KEY (`menus_id`, `users_id`),
  CONSTRAINT `fk_grades_menus1`
    FOREIGN KEY (`menus_id`)
    REFERENCES `mydb`.`menus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grades_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_grades_users1_idx` ON `mydb`.`grades` (`users_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`polls`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`polls` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`polls` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NULL,
  `result` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`options` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`options` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NULL,
  `polls_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `polls_id`),
  CONSTRAINT `fk_options_polls1`
    FOREIGN KEY (`polls_id`)
    REFERENCES `mydb`.`polls` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_options_polls1_idx` ON `mydb`.`options` (`polls_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`votes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`votes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`votes` (
  `id` INT(11) NOT NULL,
  `value` INT NOT NULL,
  `users_id` INT(11) NOT NULL,
  `options_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `options_id`),
  CONSTRAINT `fk_votes_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_votes_options1`
    FOREIGN KEY (`options_id`)
    REFERENCES `mydb`.`options` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_votes_users1_idx` ON `mydb`.`votes` (`users_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_votes_options1_idx` ON `mydb`.`votes` (`options_id` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
